---

- name: restart postgresql
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: reload nginx
  shell: nginx -t && nginx -s reload

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes


...
