{% raw -%}
---

all:
  vars:
    env: dev
  hosts:
    {% endraw %}{{ cookiecutter.vm_slug }}{% raw %}1:
      ansible_user: vagrant
      ansible_host: 192.168.11.11
  children:
    {% endraw %}{{ cookiecutter.vm_slug }}{% raw %}:
      hosts:
        {% endraw %}{{ cookiecutter.vm_slug }}{% raw %}1:

...
{% endraw -%}
