---

- name: Download certbot.
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: "{{ certbot_script }}"
    mode: 0755

- name: Check if cert exists.
  stat:
    path: "{{ certbot_dir }}/live/{{ certbot_domains[0] }}"
  register: cert_status

- name: Ensure Nginx is stopped.
  service:
    name: nginx
    state: stopped
  when: not cert_status.stat.exists

- name: Install certbot and generate cert.
  command: "{{ certbot_script }} certonly --noninteractive --agree-tos --standalone --expand --email {{ certbot_admin_email }} -d {{ certbot_domains | join(' -d ') }}"
  args:
    creates: "{{ certbot_dir }}/live/{{ certbot_domains[0] }}"

- name: Ensure Nginx is started.
  service:
    name: nginx
    state: started
  when: not cert_status.stat.exists

- name: Ensure a cron job to auto-renew the cert exists.
  cron:
    name: daily auto renew cert
    special_time: daily
    job: "{{ certbot_script }} renew --standalone --no-self-upgrade --pre-hook \"service nginx stop\" --post-hook \"service nginx start\" --quiet"
    state: present
  when: certbot_auto_renew

...
