{% raw -%}
---

all:
  vars:
    env: prod
  hosts:
    {% endraw %}{{ cookiecutter.vm_slug }}{% raw %}1:
      ansible_user: admin
      ansible_host: api.example.com
  children:
    {% endraw %}{{ cookiecutter.vm_slug }}{% raw %}:
      hosts:
        {% endraw %}{{ cookiecutter.vm_slug }}{% raw %}1:

...
{% endraw -%}
